[build]
command = "OUTPUT=netlify astro build"
publish = "dist"

[build.environment]
NETLIFY_USE_PNPM = "true"
NODE_VERSION = "20"

[[headers]]
for = "/manifest.webmanifest"

[headers.values]
Content-Type = "application/manifest+json"
